---
- name: Setup Web Server
  hosts: all
  remote_user: vagrant

  tasks:
  - name: Install Apache Server
    apt:
      name: apache2
      state: present
  - name: Add sample file
    command: echo "Hello World!" > /var/www/html/index.html
