---
- name: Setup web server with Apache
  hosts: all
  become: true
  become_method: sudo

  tasks:
  - name: Install Apache Server
    apt:
      name: apache2
      state: present

  - name: Start Apache
    service:
      name: apache2
      enabled: yes
      state: started
